### ISSUE TITLE
There is no formatter for 'ampscript' files installed.

### ISSUE THREAD

**Issue by kingfisher77** [fib-at-isobar/beautyAmp#11]
Plugin is installed. Run "Format Document" from Command Palette results in this popup message:

`There is no formatter for 'ampscript' files installed.`

What do i miss? Everything seems to be alright the feature to beautify ampscript code is not available.

**Comment by fib-at-isobar** [comment]
Hello,
this is not caused by the addon, but it's most probably a problem in your VS Code (happened to me in the past).
I would recommend:
1) restart and update VS Code
2) check if you have other addons installed that would conflict with this extension.
3) Reinstall the extension

Unfortunately the list of problems that could be causing this is rather long.
